CharityProject/CharityProject/Controllers/CharityActionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CharityData.Models;
using CharityProject;
using Microsoft.AspNetCore.Http;

namespace CharityProject.Controllers
{
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public class CharityActionsController : Controller
    {
        private readonly CharityContext _context;

        public CharityActionsController(CharityContext context)
        {
            _context = context;
        }

        // GET: CharityActions
        public async Task<IActionResult> Index()
        {
            return View(await _context.action.Where(a => a.endDateTime >= DateTime.Now).ToListAsync());
        }

        // GET: CharityActions/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charityAction = await _context.action
                .FirstOrDefaultAsync(m => m.Id == id);
            if (charityAction == null)
            {
                return NotFound();
            }

            return View(charityAction);
        }

        // GET: CharityActions/Create
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            return View();
        }

        // POST: CharityActions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,description,actionType,organizationId,creationDateTime,startDateTime,endDateTime")] CharityAction charityAction, string loggedOrg = null)
        {
            if (loggedOrg == null)
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (ModelState.IsValid)
            {
                string orgId = loggedOrg;
                if(orgId == null)
                    orgId = HttpContext.Session.GetString("idOfLoggedAccount");
                charityAction.organizationId = Guid.Parse(orgId);
                charityAction.creationDateTime = DateTime.Now;

                charityAction.Id = Guid.NewGuid();
                _context.Add(charityAction);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(charityAction);
        }

        // GET: CharityActions/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id == null)
            {
                return NotFound();
            }

            var charityAction = await _context.action.FindAsync(id);
            if (charityAction == null)
            {
                return NotFound();
            }
            return View(charityAction);
        }

        // POST: CharityActions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,name,description,actionType,organizationId,creationDateTime,startDateTime,endDateTime")] CharityAction charityAction)
        {
            if (id != charityAction.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(charityAction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CharityActionExists(charityAction.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(charityAction);
        }

        // GET: CharityActions/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var charityAction = await _context.action
                .FirstOrDefaultAsync(m => m.Id == id);
            if (charityAction == null)
            {
                return NotFound();
            }

            return View(charityAction);
        }

        // POST: CharityActions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var charityAction = await _context.action.FindAsync(id);
            _context.action.Remove(charityAction);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CharityActionExists(Guid id)
        {
            return _context.action.Any(e => e.Id == id);
        }
    }
}

CharityProject/CharityProject/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CharityData.Models;
using CharityProject;
using Microsoft.AspNetCore.Http;

namespace CharityProject.Controllers
{

    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public class OrganizationsController : Controller
    {
        private readonly CharityContext _context;

        public OrganizationsController(CharityContext context)
        {
            _context = context;
        }

        // GET: Organizations
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            var currentLoggedUser = HttpContext.Session.GetString("idOfLoggedUserAccount");
            var currentLoggedUserObject = _context.user.FirstOrDefault(u => u.UserAccount.ToString() == currentLoggedUser);
            var creditCard = currentLoggedUserObject.creditCardId;
            ViewBag.creditCardId = creditCard.ToString();
            return View(await _context.organization.ToListAsync());
        }

        // GET: Organizations/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.organization
                .FirstOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }

            var account = await _context.account.FindAsync(organization.UserAccount);
            var image = _context.image.FirstOrDefault(a => a.Id.ToString().Equals(account.imageId.ToString()));
            if (image != null) ViewData["ImageURL"] = image.Path;
            
            return View(organization);
        }

        // GET: Organizations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Organizations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,dateOfFounding,description")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                organization.Id = Guid.NewGuid();
                HttpContext.Session.SetString("registrationId", (organization.Id).ToString());
                HttpContext.Session.SetString("registrationName", organization.name);
                HttpContext.Session.SetString("registrationDateOfFounding", organization.dateOfFounding.ToString());
                HttpContext.Session.SetString("registrationDescription", organization.description);
                organization.Id = Guid.NewGuid();
                //_context.Add(organization);
                await _context.SaveChangesAsync();
                return RedirectToAction("CreateOrganizationAccount", "Account");
            }
            return View(organization);
        }

        // GET: Organizations/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.organization.FindAsync(id);
            var account = await _context.account.FindAsync(organization.UserAccount);
            var image = _context.image.FirstOrDefault(a => a.Id.ToString().Equals(account.imageId.ToString()));
            if (image != null) ViewData["ImageURL"] = image.Path;

            if (organization == null)
            {
                return NotFound();
            }
            return View(organization);
        }

        // POST: Organizations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,name,UserAccount,dateOfFounding,description,creditCardNumber")] Organization organization)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id != organization.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(organization);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrganizationExists(organization.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(organization);
        }

        // GET: Organizations/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.organization
                .FirstOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }

            return View(organization);
        }

        // POST: Organizations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var organization = await _context.organization.FindAsync(id);
            _context.organization.Remove(organization);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrganizationExists(Guid id)
        {
            return _context.organization.Any(e => e.Id == id);
        }

        // GET: Users/Donate/5
        public async Task<IActionResult> Donate(Guid? id)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.organization.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var currentLoggedUser = HttpContext.Session.GetString("idOfLoggedUserAccount");
            var currentLoggedUserObject = _context.user.Where(u => u.UserAccount.ToString() == currentLoggedUser).Single();
            var creditCard = currentLoggedUserObject.creditCardId;
            var creditCardObject = _context.card.Where(c => c.Id == creditCard).Single();
            HttpContext.Session.SetString("donatingTo", user.name);
            HttpContext.Session.SetString("AccountFunds", creditCardObject.amount.ToString());
            HttpContext.Session.SetString("TransferringFrom", currentLoggedUserObject.Id.ToString());
            HttpContext.Session.SetString("TransferringTo", id.ToString());

            return RedirectToAction("Create", "Payments");
        }
    }
}

CharityProject/CharityProject/Views/Organizations/Create.cshtml
@model CharityData.Models.Organization

@{
    ViewData["Title"] = "CreateOrganizationAccount";
}

<h2>Create</h2>

<h4>Organization</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dateOfFounding" class="control-label"></label>
                <input asp-for="dateOfFounding" class="form-control" />
                <span asp-validation-for="dateOfFounding" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div class="control-label">Step 1 of 2</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CharityProject/CharityProject/Views/Organizations/Delete.cshtml
@model CharityData.Models.Organization

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Organization</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserAccount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserAccount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.dateOfFounding)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dateOfFounding)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.creditCardNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.creditCardNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CharityProject/CharityProject/Views/Organizations/Details.cshtml
@model CharityData.Models.Organization

@{
    ViewData["Title"] = "Details";
}
<h2>Details</h2>

<h4>Organization</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="name" class="control-label">Name</label>
            <input asp-for="name" class="form-control" readonly />
            <span asp-validation-for="name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UserAccount" class="control-label">User Account</label>
            <input asp-for="UserAccount" class="form-control" readonly />
            <span asp-validation-for="UserAccount" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="dateOfFounding" class="control-label">Foundation date</label>
            <input asp-for="dateOfFounding" class="form-control" readonly />
            <span asp-validation-for="dateOfFounding" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="description" class="control-label">Description</label>
            <input asp-for="description" class="form-control" readonly />
            <span asp-validation-for="description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="creditCardNumber" class="control-label">Credit card</label>
            <input asp-for="creditCardNumber" class="form-control" readonly />
            <span asp-validation-for="creditCardNumber" class="text-danger"></span>
        </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-4">
        <div class="form-group">
            <label class="control-label">Image</label>
            <div>
                <img src="@ViewData["ImageURL"]" height="400">
            </div>

        </div>

        <div>
            <p>

            </p>
        </div>
    </div>
</div>

<input class="btn btn-default" type="button" value="Add action" onclick="@("window.location.href='" + @Url.Action("Create", "CharityActions") + "'");" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CharityProject/CharityProject/Views/Organizations/Edit.cshtml
@model CharityData.Models.Organization

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Organization</h4>
<hr />
<div class="row">
    <div class="row">
        <form asp-action="Edit">
            <div class="col-md-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="name" class="control-label">Name</label>
                    <input asp-for="name" class="form-control" />
                    <span asp-validation-for="name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UserAccount" class="control-label">User Account</label>
                    <input asp-for="UserAccount" class="form-control" />
                    <span asp-validation-for="UserAccount" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="dateOfFounding" class="control-label">Foundation date</label>
                    <input asp-for="dateOfFounding" class="form-control" />
                    <span asp-validation-for="dateOfFounding" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="description" class="control-label">Description</label>
                    <input asp-for="description" class="form-control" />
                    <span asp-validation-for="description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="creditCardNumber" class="control-label">Credit card</label>
                    <input asp-for="creditCardNumber" class="form-control" />
                    <span asp-validation-for="creditCardNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-4">
                <div class="form-group left">
                    <label asp-for="description" class="control-label">Image</label>
                    <div>
                        <img src="@ViewData["ImageURL"]" height="400">
                    </div>

                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
    <div>
        @{ViewDataDictionary dictionary = new ViewDataDictionary(ViewData);
            dictionary.Add("id", Model.Id);
            dictionary.Add("UserAccount", Model.UserAccount);
        }
        @{await Html.RenderPartialAsync("_ImageForm", dictionary);}
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @*function editImage() {
            document.getElementById("editImageForm").hidden = false;
            //document.getElementById("form").submit();
        }*@
}

CharityProject/CharityProject/Views/Organizations/Index.cshtml
@model IEnumerable<CharityData.Models.Organization>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<!--<input asp-action="Create" type="button" class="btn btn-default" value="Create new">-->

<table class="table">
    <thead>
        <tr class="text-center">
            <th class="text-center">
                Organization name
            </th>
            <!--
            <th  class="text-center">
                User Account
            </th>
             -->
            <th class="text-center">
                Date of Foundation
            </th>
            <th class="text-center">
                Description
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <!--<td>
        @Html.DisplayFor(modelItem => item.UserAccount)
     </td>
    -->
            <td>
                @Html.DisplayFor(modelItem => item.dateOfFounding)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            @if (item.creditCardNumber.ToString() != "00000000-0000-0000-0000-000000000000" && ViewBag.creditCardId != "00000000-0000-0000-0000-000000000000")
            {
                <td>
                    <a asp-action="Donate" asp-route-id="@item.Id">Transfer money</a> 

                </td>
            }
            else
            {
                <td>

                </td>
            }
            <!--
       <td>
       <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
       <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
       <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
       </td>
    -->
        </tr>
        }
    </tbody>
</table>