CharityProject/CharityProject/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CharityData.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CharityProject.Controllers
{
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public class ImagesController : Controller
    {
        private CharityContext _context;
        public ImagesController(CharityContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        [HttpPost]
        public async Task <IActionResult> Edit(Image image)
        {
            var ourImage = await  _context.image.FindAsync(image.Id);
            if (ourImage != null)
            {
                ourImage.Path = image.Path;
            }
            else
            {
                _context.image.Add(image);
            }

            await _context.SaveChangesAsync();

            return View();
        }
    }
}

CharityProject/CharityProject/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CharityData.Models;
using CharityProject;
using Microsoft.AspNetCore.Http;

namespace CharityProject.Controllers
{

    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public class OrganizationsController : Controller
    {
        private readonly CharityContext _context;

        public OrganizationsController(CharityContext context)
        {
            _context = context;
        }

        // GET: Organizations
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            var currentLoggedUser = HttpContext.Session.GetString("idOfLoggedUserAccount");
            var currentLoggedUserObject = _context.user.FirstOrDefault(u => u.UserAccount.ToString() == currentLoggedUser);
            var creditCard = currentLoggedUserObject.creditCardId;
            ViewBag.creditCardId = creditCard.ToString();
            return View(await _context.organization.ToListAsync());
        }

        // GET: Organizations/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.organization
                .FirstOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }

            var account = await _context.account.FindAsync(organization.UserAccount);
            var image = _context.image.FirstOrDefault(a => a.Id.ToString().Equals(account.imageId.ToString()));
            if (image != null) ViewData["ImageURL"] = image.Path;
            
            return View(organization);
        }

        // GET: Organizations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Organizations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,dateOfFounding,description")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                organization.Id = Guid.NewGuid();
                HttpContext.Session.SetString("registrationId", (organization.Id).ToString());
                HttpContext.Session.SetString("registrationName", organization.name);
                HttpContext.Session.SetString("registrationDateOfFounding", organization.dateOfFounding.ToString());
                HttpContext.Session.SetString("registrationDescription", organization.description);
                organization.Id = Guid.NewGuid();
                //_context.Add(organization);
                await _context.SaveChangesAsync();
                return RedirectToAction("CreateOrganizationAccount", "Account");
            }
            return View(organization);
        }

        // GET: Organizations/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.organization.FindAsync(id);
            var account = await _context.account.FindAsync(organization.UserAccount);
            var image = _context.image.FirstOrDefault(a => a.Id.ToString().Equals(account.imageId.ToString()));
            if (image != null) ViewData["ImageURL"] = image.Path;

            if (organization == null)
            {
                return NotFound();
            }
            return View(organization);
        }

        // POST: Organizations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,name,UserAccount,dateOfFounding,description,creditCardNumber")] Organization organization)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id != organization.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(organization);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrganizationExists(organization.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(organization);
        }

        // GET: Organizations/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.organization
                .FirstOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }

            return View(organization);
        }

        // POST: Organizations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var organization = await _context.organization.FindAsync(id);
            _context.organization.Remove(organization);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrganizationExists(Guid id)
        {
            return _context.organization.Any(e => e.Id == id);
        }

        // GET: Users/Donate/5
        public async Task<IActionResult> Donate(Guid? id)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.organization.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var currentLoggedUser = HttpContext.Session.GetString("idOfLoggedUserAccount");
            var currentLoggedUserObject = _context.user.Where(u => u.UserAccount.ToString() == currentLoggedUser).Single();
            var creditCard = currentLoggedUserObject.creditCardId;
            var creditCardObject = _context.card.Where(c => c.Id == creditCard).Single();
            HttpContext.Session.SetString("donatingTo", user.name);
            HttpContext.Session.SetString("AccountFunds", creditCardObject.amount.ToString());
            HttpContext.Session.SetString("TransferringFrom", currentLoggedUserObject.Id.ToString());
            HttpContext.Session.SetString("TransferringTo", id.ToString());

            return RedirectToAction("Create", "Payments");
        }
    }
}

CharityProject/CharityProject/Views/Shared/Image.cshtml
@model CharityData.Models.Image
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="form-group">
    <label class="control-label"> Image URL</label>
    <input id="newImageURL" value="@ViewData["ImageURL"]" type="url" class="form-control" />
</div>
<form asp-action="Edit" asp-controller="Image">
    <div class="form-group">
        <label>New Image URL</label>
        <input asp-for="Path" type="url" class="form-control">
    </div>
    <div class="form-group">
        <input type="submit" value="Update image" class="btn btn-default">
    </div>
</form>
<dt>
    <p>Image</p>
</dt>
<dd>
    <div class="form-group">
        <img src="@ViewData["ImageURL"]" height="400">
    </div>
</dd>

CharityProject/CharityProject/Views/Shared/_ImageForm.cshtml
<input type="button" value="Edit photo" class="btn btn-default" id="editImage" />
@{
    var id = (Guid)ViewData["id"];
    var UserAccount = (Guid)ViewData["UserAccount"];

 }


@using (Html.BeginForm("Edit", "Images", FormMethod.Post))
{
    <text>
        <div id="editImageForm" class="form-group">
            <label for="imgUrl">New Url</label>
            <input value="@UserAccount" name="UserAccount" class="form-control hidden" />
            <input value="@id" name="id" class="form-control hidden" />
            <input id="imgUrl" name="imgUrl" type="url" />
            <input type="submit" value="Save photo" class="btn btn-default" id="saveImage" />
        </div>
    </text>
}

CharityProject/CharityProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Charity Project</title>

    <environment>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css?@DateTime.Now.Ticks" />
        <link rel="stylesheet" href="~/css/site.css?@DateTime.Now.Ticks" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CharityProject</a>
            </div>
            @if (Context.Session.GetString("username") != null)
            {
                @if (Context.Session.GetInt32("IsUser") == 1)
                {
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-area="" asp-controller="Users" asp-action="MyProfile">My Profile</a></li>
                            <li><a asp-area="" asp-controller="Organizations" asp-action="Index">Organizations</a></li>
                            <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                            <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
                        </ul>
                    </div>
                }
                @if (Context.Session.GetInt32("IsUser") == 0)
                {
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">My Profile</a></li>
                            <li><a asp-area="" asp-controller="Organizations" asp-action="Index">Organizations</a></li>
                            <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                            <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
                        </ul>
                    </div>
                }
            }

        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - CharityProject</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>