CharityProject/CharityProject/Controllers/ActionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CharityData.Models;
using CharityProject;
using Microsoft.AspNetCore.Http;

namespace CharityProject.Controllers
{
    public class ActionsController : Controller
    {
        private readonly CharityContext _context;

        public ActionsController(CharityContext context)
        {
            _context = context;
        }

        // GET: Actions
        public async Task<IActionResult> Index()
        {
            return View(await _context.action.Where(a => a.endDateTime >= DateTime.Now).ToListAsync());
        }

        // GET: Actions/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var action = await _context.action
                .FirstOrDefaultAsync(m => m.Id == id);
            if (action == null)
            {
                return NotFound();
            }

            return View(action);
        }

        // GET: Actions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,description,actionType,startDateTime,endDateTime")] CharityData.Models.Action action)
        {
            string organizationUsername = HttpContext.Session.GetString("username");
            var account = await _context.account.FirstOrDefaultAsync(m => m.username == organizationUsername);
            if (account == null)
            {
                return NotFound();
            }

            var org = await _context.organization.FirstOrDefaultAsync(m => m.UserAccount == account.Id);
            if (org == null)
            {
                return NotFound();
            }

            action.organizationId = org.Id;
            action.creationDateTime = DateTime.Now;

            if (ModelState.IsValid)
            {
               
                action.Id = Guid.NewGuid();
                _context.Add(action);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //var errors = ModelState.Values.SelectMany(v => v.Errors);
            return View(action);
        }

        // GET: Actions/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var action = await _context.action.FindAsync(id);
            if (action == null)
            {
                return NotFound();
            }
            return View(action);
        }

        // POST: Actions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,name,description,actionType,organizationId,creationDateTime,startDateTime,endDateTime")] CharityData.Models.Action action)
        {
            if (id != action.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(action);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActionExists(action.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(action);
        }

        // GET: Actions/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var action = await _context.action
                .FirstOrDefaultAsync(m => m.Id == id);
            if (action == null)
            {
                return NotFound();
            }

            return View(action);
        }

        // POST: Actions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var action = await _context.action.FindAsync(id);
            _context.action.Remove(action);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActionExists(Guid id)
        {
            return _context.action.Any(e => e.Id == id);
        }
    }
}

CharityProject/CharityProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CharityProject.Models;
using Microsoft.AspNetCore.Http;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;

namespace CharityProject.Controllers
{
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public class HomeController : Controller
    {

        private readonly CharityContext _context;

        public HomeController(CharityContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string loggedUsr = null)
        {
            if (loggedUsr == null)
            {
                if (HttpContext.Session.GetString("username") == null)
                    return RedirectToAction("", "");

                if (HttpContext.Session.GetInt32("IsUser") == 0)
                {
                    return RedirectToAction("Details", "Organizations", new { id = HttpContext.Session.GetString("idOfLoggedAccount") });
                }
            }
            var activeActions = await _context.action.Where(a => a.endDateTime >= DateTime.Now && a.startDateTime <= DateTime.Now).ToListAsync();
            var pastActions = await _context.action.Where(a => a.endDateTime < DateTime.Now).ToListAsync();
            var futureActions = await _context.action.Where(a => a.startDateTime > DateTime.Now).ToListAsync();

            List<String> namesOfOrg = new List<String>();
            List<String> namesOfOrg2 = new List<String>();
            List<String> namesOfOrg3 = new List<String>();
            foreach (var oneAction in activeActions)
            {
                Guid idActionOrg = oneAction.organizationId;
                CharityData.Models.Organization foundOrg = _context.organization.Where(a => a.Id == idActionOrg).First();
                namesOfOrg.Add(foundOrg.name);
            }
            foreach (var oneAction in pastActions)
            {
                Guid idActionOrg = oneAction.organizationId;
                CharityData.Models.Organization foundOrg = _context.organization.Where(a => a.Id == idActionOrg).First();
                namesOfOrg2.Add(foundOrg.name);
            }
            foreach (var oneAction in futureActions)
            {
                Guid idActionOrg = oneAction.organizationId;
                CharityData.Models.Organization foundOrg = _context.organization.Where(a => a.Id == idActionOrg).First();
                namesOfOrg3.Add(foundOrg.name);
            }
            ViewBag.namesOfOrg = namesOfOrg;
            ViewBag.activeActions = activeActions;

            ViewBag.namesOfOrg2 = namesOfOrg2;
            ViewBag.pastActions = pastActions;

            ViewBag.namesOfOrg3 = namesOfOrg3;
            ViewBag.futureActions = futureActions;
            return View();
        }

        public IActionResult About()
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (HttpContext.Session.GetInt32("IsUser") == 0)
            {
                return RedirectToAction("Details", "Organizations", new { id = HttpContext.Session.GetString("idOfLoggedAccount") });
            }
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (HttpContext.Session.GetInt32("IsUser") == 0)
            {
                return RedirectToAction("Details", "Organizations", new { id = HttpContext.Session.GetString("idOfLoggedAccount") });
            }
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CharityProject/CharityProject/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CharityProject/CharityProject/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CharityProject/CharityProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.jpg" alt="Charity System" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p style="color: black">
                    Single system for all kinds of charity actions.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.jpg" alt="Donations" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p style="color: black">
                    Donate books, clothes, groceries or help elderly people.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.png" alt="Red Cross" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p style="color: black">
                    Participate in Red Cross actions: donate blood, charity races or help clean a local park.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<!--<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>
 -->
<!--<input class="btn btn-default" type="button" value="Show active actions" onclick="@("window.location.href='" + @Url.Action("Index", "Actions") + "'");" />
    -->

<script>
    function togglediv(id) {
        var div = document.getElementById(id);
        div.style.display = div.style.display == "none" ? "block" : "none";
    }
</script>
<div class="row">
    <div class="col-md-3">
        <button id="activeButton" onclick="togglediv('activeActions')">Show/Hide Active Actions</button>
    </div>
    <div class="col-md-3">
        <button id="pastButton" onclick="togglediv('pastActions')">Show/Hide Past Actions</button>
    </div>
    <div class="col-md-3">
        <button id="futureButton" onclick="togglediv('futureActions')">Show/Hide Future Actions</button>
    </div>
</div>
<div id="activeActions" style="display: none">
    <h2>Active Actions</h2>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Action name
                </th>
                <th>
                    Description
                </th>
                <th>
                    Organization Name
                </th>
                <th>
                    Start date
                </th>
                <th>
                    End date
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                var orgNames = ViewBag.namesOfOrg;
                var actions = ViewBag.activeActions;
                for (int i = 0; i < actions.Count; i++)
                {
                    <tr>
                        <td>
                            @actions[i].name
                        </td>
                        <td>
                            @actions[i].description
                        </td>
                        <td>
                            @orgNames[i]

                        </td>
                        <td>
                            @actions[i].startDateTime
                        </td>
                        <td>
                            @actions[i].endDateTime
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
</div>

<div id="pastActions" style="display: none">
    <h2>Past Actions</h2>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Action name
                </th>
                <th>
                    Description
                </th>
                <th>
                    Organization Name
                </th>
                <th>
                    Start date
                </th>
                <th>
                    End date
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                var orgNames2 = ViewBag.namesOfOrg2;
                var actions2 = ViewBag.pastActions;
                for (int i = 0; i < actions2.Count; i++)
                {
                    <tr>
                        <td>
                            @actions2[i].name
                        </td>
                        <td>
                            @actions2[i].description
                        </td>
                        <td>
                            @orgNames2[i]

                        </td>
                        <td>
                            @actions2[i].startDateTime
                        </td>
                        <td>
                            @actions2[i].endDateTime
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
</div>

<div id="futureActions" style="display: none">
    <h2>Future Actions</h2>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Action name
                </th>
                <th>
                    Description
                </th>
                <th>
                    Organization Name
                </th>
                <th>
                    Start date
                </th>
                <th>
                    End date
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                var orgNames3 = ViewBag.namesOfOrg3;
                var actions3 = ViewBag.futureActions;
                for (int i = 0; i < actions3.Count; i++)
                {
                    <tr>
                        <td>
                            @actions3[i].name
                        </td>
                        <td>
                            @actions3[i].description
                        </td>
                        <td>
                            @orgNames3[i]

                        </td>
                        <td>
                            @actions3[i].startDateTime
                        </td>
                        <td>
                            @actions3[i].endDateTime
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
</div>