CharityProject/CharityProject/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CharityData.Models;
using Microsoft.AspNetCore.Http;

namespace CharityProject
{
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public class CardsController : Controller
    {
        private readonly CharityContext _context;

        public CardsController(CharityContext context)
        {
            _context = context;
        }

        // GET: Cards
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            return View(await _context.card.ToListAsync());
        }

        // GET: Cards/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.card
                .FirstOrDefaultAsync(m => m.Id == id);
            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // GET: Cards/Create
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            return View();
        }

        // POST: Cards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,dateOfExpiry,bankName,amount,creditCardNumber")] Card card, string loggedUsr = null)
        {
            if (loggedUsr == null)
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (ModelState.IsValid)
            {
                card.Id = Guid.NewGuid();
                string idOfLoggedAccount = loggedUsr;
                if (loggedUsr == null)
                { 
                    idOfLoggedAccount = HttpContext.Session.GetString("idOfLoggedAccount");
                }
                

                var loggedUser = _context.user.Where(u => u.Id.ToString() == idOfLoggedAccount).Single();
                loggedUser.creditCardId = card.Id;
                _context.Add(card);
                await _context.SaveChangesAsync();
                return RedirectToAction("", "Home");
            }
            return View(card);
        }

        // GET: Cards/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.card.FindAsync(id);
            if (card == null)
            {
                return NotFound();
            }
            return View(card);
        }

        // POST: Cards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,dateOfExpiry,bankName,amount,creditCardNumber")] Card card)
        {
            if (id != card.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(card);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CardExists(card.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(card);
        }

        // GET: Cards/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.card
                .FirstOrDefaultAsync(m => m.Id == id);
            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // POST: Cards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var card = await _context.card.FindAsync(id);
            _context.card.Remove(card);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CardExists(Guid id)
        {
            return _context.card.Any(e => e.Id == id);
        }
    }
}

CharityProject/CharityProject/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CharityData.Models;
using CharityProject;
using Microsoft.AspNetCore.Http;

namespace CharityProject.Controllers
{
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public class ItemsController : Controller
    {
        private readonly CharityContext _context;

        public ItemsController(CharityContext context)
        {
            _context = context;
        }

        // GET: Items
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            return View(await _context.item.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.item
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,description,value,userDonatedId")] Item item, string loggedUser = null)
        {
            if (loggedUser == null)
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (ModelState.IsValid)
            {
                string userUsername = loggedUser;
                if (loggedUser == null)
                    userUsername = HttpContext.Session.GetString("username");
                
                var account = await _context.account.FirstOrDefaultAsync(m => m.username == userUsername);
                if (account == null)
                {
                    return NotFound();
                }

                var user = await _context.user.FirstOrDefaultAsync(m => m.UserAccount == account.Id);
                if (user == null)
                {
                    return NotFound();
                }
                item.Id = Guid.NewGuid();
                item.userDonatedId = user.Id;
                _context.Add(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.item.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,name,description,value,userDonatedId")] Item item)
        {
            if (HttpContext.Session.GetString("username") == null)
                return RedirectToAction("", "");
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.item
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var item = await _context.item.FindAsync(id);
            _context.item.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(Guid id)
        {
            return _context.item.Any(e => e.Id == id);
        }
    }
}

CharityProject/CharityProject/Views/Users/Create.cshtml
@model CharityData.Models.User

@{
    ViewData["Title"] = "CreateUserAccount";
}

<h2>Create</h2>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>
            <div class="from-group">
                <label asp-for="gender" class="control-label"></label>
                <select asp-for="gender" asp-items="Model.genders"></select>
            </div>
            <div class="form-group">
                <label asp-for="dateOfBirth" class="control-label"></label>
                <input asp-for="dateOfBirth" class="form-control" />
                <span asp-validation-for="dateOfBirth" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div class="control-label">Step 1 of 2</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CharityProject/CharityProject/Views/Users/Delete.cshtml
@model CharityData.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserAccount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserAccount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.dateOfBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dateOfBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.creditCardId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.creditCardId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CharityProject/CharityProject/Views/Users/Details.cshtml
@model CharityData.Models.User

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserAccount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserAccount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.dateOfBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dateOfBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.creditCardId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.creditCardId)
        </dd>
    </dl>
    <div class="form-group">
        <label class="control-label">Image</label>
        <div>
            <img src="@ViewData["ImageURL"]" height="400">
        </div>

    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
<div>
    <h2>History of donated items</h2>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Item name
                </th>
                <th>
                    Description
                </th>
                <th>
                    Value
                </th>
                <th>
                    Action name
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                var donatedItems = ViewBag.items;
                var actDoneted = ViewBag.actDoneted;
                for (int i = 0; i < donatedItems.Count; i++)
                {
                    <tr>
                        <td>
                            @donatedItems[i].name
                        </td>
                        <td>
                            @donatedItems[i].description
                        </td>
                        <td>
                            @donatedItems[i].value
                        </td>
                        <td>
                            @actDoneted[i].name
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<div>
    <h2>History of payments</h2>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name of organization
                </th>
                <th>
                    Donated amout
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                var payments = ViewBag.payments;
                var organizations = ViewBag.organizations;
                for (int i = 0; i < payments.Count; i++)
                {
                    <tr>
                        <td>
                            @organizations[i].name
                        </td>
                        <td>
                            @payments[i].amount
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<div>
    <h2>History of actions participated in</h2>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Action name
                </th>
                <th>
                    Description
                </th>
                <th>
                    Organization name
                </th>
                <th>
                    Start date and time
                </th>
                <th>
                    End date and time
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                var myAction = ViewBag.myActions;
                var organizedBy = ViewBag.organizedBy;
                for (int i = 0; i < myAction.Count; i++)
                {
                    <tr>
                        <td>
                            @myAction[i].name
                        </td>
                        <td>
                            @myAction[i].description
                        </td>
                        <td>
                            @organizedBy[i].name
                        </td>
                        <td>
                            @myAction[i].startDateTime
                        </td>
                        <td>
                            @actDoneted[i].endDateTime
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<input class="btn btn-default" type="button" value="Add item" onclick="@("window.location.href='" + @Url.Action("Create", "Items") + "'");" />
@if (ViewBag.showButton == 1)
{
    <input class="btn btn-default" type="button" value="Add card" onclick="@("window.location.href='" + @Url.Action("Create", "Cards") + "'");" />
}

CharityProject/CharityProject/Views/Users/Edit.cshtml
@model CharityData.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>User</h4>
<hr />
<div class="row">
    <form asp-action="Edit">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <!--
    <div class="form-group">
        <label asp-for="UserAccount" class="control-label"></label>
        <input asp-for="UserAccount" class="form-control" />
        <span asp-validation-for="UserAccount" class="text-danger"></span>
    </div>
        -->
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <input asp-for="gender" class="form-control" />
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dateOfBirth" class="control-label"></label>
                <input asp-for="dateOfBirth" class="form-control" />
                <span asp-validation-for="dateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="creditCardId" class="control-label"></label>
                <input asp-for="creditCardId" class="form-control" />
                <span asp-validation-for="creditCardId" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">Image</label>
                <div>
                    <img src="@ViewData["ImageURL"]" height="400">
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </form>
</div>
<div>
    @{ViewDataDictionary dictionary = new ViewDataDictionary(ViewData);
        dictionary.Add("id", Model.Id);
        dictionary.Add("UserAccount", Model.UserAccount);
    }
    @{await Html.RenderPartialAsync("_ImageForm", dictionary);}
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CharityProject/CharityProject/Views/Users/Index.cshtml
@model IEnumerable<CharityData.Models.User>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<!--
<p>
    <a asp-action="Create">Create New</a>
</p>
    -->
<table class="table">
    <thead>
        <tr>
            <!--
    <th>
        @Html.DisplayNameFor(model => model.UserAccount)
    </th>
        -->
            <th>
                @Html.DisplayNameFor(model => model.firstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.lastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dateOfBirth)
            </th>
            <!--
    <th>
        @Html.DisplayNameFor(model => model.creditCardId)
    </th>
        -->
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <!--
    <td>
        @Html.DisplayFor(modelItem => item.UserAccount)
    </td>
    -->
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dateOfBirth)
            </td>
            
            <!--
    <td>
        @Html.DisplayFor(modelItem => item.creditCardId)
    </td>
    -->
            <!--
        <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
        </td>
    -->
        </tr>
        }
    </tbody>
</table>